# Generated by Django 2.2.10 on 2020-03-10 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('processing', 'Análise do curriculo em processamento'), ('approved', 'Candidato aprovado'), ('reproved', 'Candidato reprovado'), ('quarantine', 'Candidato em quarentena')], default='processing', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
