# Generated by Django 2.2.10 on 2020-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.CharField(default='20', max_length=250),
            preserve_default=False,
        ),
    ]
