# Generated by Django 2.2.10 on 2020-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='grade',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
